chore(router): remove validation for post parameters (#5592)
# Description

Removing `ValidatePostInfo` since it isn't really validating anything at
all and it accounts for 10% of the overall `processDestinationJobs`
time.
```go
func TestValidatePostInfo(t *testing.T) {
	err := ValidatePostInfo(PostParametersT{})
	require.Error(t, err)
}
```
```sh
=== RUN   TestValidatePostInfo
    /Users/aristzoumas/work/rudder-server/processor/integrations/integrations_test.go:11:
        	Error Trace:	/Users/aristzoumas/work/rudder-server/processor/integrations/integrations_test.go:11
        	Error:      	An error is expected but got nil.
        	Test:       	TestValidatePostInfo
--- FAIL: TestValidatePostInfo (0.00s)
```
<img width="1110" alt="Screenshot 2025-03-12 at 1 05 12 PM"
src="https://github.com/user-attachments/assets/c1915377-cd44-44b4-b7ad-4438ebe299b3"
/>

## Linear Ticket

resolves PIPE-1965

## Security

- [x] The code changed/added as part of this pull request won't create
any security issues with how the software is being used.